services:
  backend:
    build: .
    container_name: email-analyzer-api
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY_EMAIL_ANALYZER=${OPENAI_API_KEY_EMAIL_ANALYZER}
      - MAX_UPLOAD_SIZE=16777216
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: email-analyzer-front
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: email-analyzer-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
